package com.uvod.common.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * DTO representing authenticated user data extracted
 * from the x-ms-client-principal header of Azure Static Web Apps.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ClientPrincipal {

    /** Unique user ID (generated by SWA) */
    private String userId;

    /** Username or email of the user (from provider) */
    private String userDetails;

    /** Authentication provider (e.g. "github", "aad") */
    private String identityProvider;

    /** Roles assigned to the user */
    private List<String> userRoles;
}