
FROM maven:3.9-eclipse-temurin-17 AS builder

WORKDIR /app


COPY pom.xml .
RUN mvn dependency:go-offline


COPY src ./src
RUN mvn package -DskipTests


FROM mcr.microsoft.com/openjdk/jdk:17

WORKDIR /app


RUN groupadd -r uvod && useradd -r -g uvod uvod
USER uvod

# Supposing only one jar is in the dir
COPY --from=builder /app/target/*.jar app.jar


EXPOSE 8080


ENTRYPOINT ["java", "-jar", "app.jar"]